// Given two strings s and t which consist of only lowercase letters.
// String t is generated by random shuffling string s and then add one more
// letter at a random position.
// Find the letter that was added in t.

func findTheDifference(s string, t string) byte {
    letters := map[rune]int{}
    for _, letter := range s {
        letters[letter]++
    }
    for _, letter := range t {
        if letters[letter] == 0 {
            return byte(letter)
        }
        letters[letter]--
    }
    return 0
}
